apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    tier: backend
spec:
  type: ClusterIP
  ports:
    - name: "backend-service"
      port: 8080
      targetPort: 8080
  selector:
    tier: backend