apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - name: "frontend-service"
      port: 3000
      targetPort: 80
  selector:
    tier: frontend