apiVersion: v1
kind: Pod
metadata:
  name: curl-load-generator
spec:
  containers:
  - name: curl-container
    image: curlimages/curl
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; 
      do 
        curl -X POST http://172.18.0.4:8080/api/ \
        -H "Content-Type: application/json" \
        -d '"time": "Mon Apr 20 2026 12:05:05 GMT-0700 (Pacific Daylight Time)"' \
        --silent;
        sleep 0.1; 
      done
